import { type FormEvent, useMemo, useState } from 'react';
import { publishScoreEventRequestSchema, type PublishScoreEventResponse } from '@/features/leaderboard/model/schemas';
import { usePublishScoreEvent } from '@/features/leaderboard/hooks/usePublishScoreEvent';
import { ErrorBanner } from '@/shared/components/ErrorBanner';

function createClientEventId(): string {
  const random = typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
  return `ui-${random}`;
}

function optionalText(value: FormDataEntryValue | null): string | undefined {
  if (typeof value !== 'string') {
    return undefined;
  }
  const normalized = value.trim();
  return normalized.length > 0 ? normalized : undefined;
}

function optionalNumber(value: FormDataEntryValue | null): number | undefined {
  if (typeof value !== 'string') {
    return undefined;
  }
  const normalized = value.trim();
  if (normalized.length === 0) {
    return undefined;
  }
  const parsed = Number(normalized);
  return Number.isFinite(parsed) ? parsed : Number.NaN;
}

export function ScoreEventForm() {
  const mutation = usePublishScoreEvent();
  const [mode, setMode] = useState<'delta' | 'absoluteScore'>('delta');
  const [eventId, setEventId] = useState(createClientEventId);
  const [validationError, setValidationError] = useState<string | null>(null);
  const [lastResponse, setLastResponse] = useState<PublishScoreEventResponse | null>(null);

  const scoreLabel = useMemo(() => (mode === 'delta' ? 'Score delta' : 'Absolute score'), [mode]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formElement = event.currentTarget;
    setLastResponse(null);
    setValidationError(null);
    mutation.reset();

    const form = new FormData(formElement);
    const score = optionalNumber(form.get('score'));

    // The backend requires exactly one score mode. The UI maps the selected mode into that contract.
    const parsed = publishScoreEventRequestSchema.safeParse({
      eventId: optionalText(form.get('eventId')) ?? eventId,
      leaderboardId: optionalText(form.get('leaderboardId')) ?? 'global',
      itemId: optionalText(form.get('itemId')),
      displayName: optionalText(form.get('displayName')),
      delta: mode === 'delta' ? score : undefined,
      absoluteScore: mode === 'absoluteScore' ? score : undefined
    });

    if (!parsed.success) {
      setValidationError(parsed.error.issues[0]?.message ?? 'Please correct the highlighted fields.');
      return;
    }

    try {
      const response = await mutation.mutateAsync(parsed.data);
      setLastResponse(response);
      formElement.reset();
      setEventId(createClientEventId());
      setMode('delta');
    } catch {
      // Mutation error is rendered through ErrorBanner from TanStack Query state.
    }
  }

  return (
    <section className="form-card">
      <h2>Publish score event</h2>
      <p>Send a validated event to the backend smoke endpoint. The backend publishes it to Kafka.</p>
      {validationError ? <div className="error-banner" role="alert"><strong>Validation failed.</strong><span>{validationError}</span></div> : null}
      {mutation.error ? <ErrorBanner error={mutation.error} /> : null}
      {lastResponse ? (
        <div className="success-banner" role="status">
          Event accepted: <strong>{lastResponse.eventId}</strong> · {lastResponse.topic} partition {lastResponse.partition} offset{' '}
          {lastResponse.offset}
        </div>
      ) : null}
      <form onSubmit={(submitEvent) => { void handleSubmit(submitEvent); }} noValidate>
        <div className="form-grid">
          <div className="form-field">
            <label htmlFor="eventId">Event ID</label>
            <span className="field-hint">Generated by the UI so Kafka retries and backend idempotency can deduplicate safely.</span>
            <div className="inline-field">
              <input
                id="eventId"
                name="eventId"
                maxLength={120}
                autoComplete="off"
                value={eventId}
                onChange={(changeEvent) => {
                  setEventId(changeEvent.target.value);
                }}
              />
              <button type="button" className="button button--secondary" onClick={() => {
                  setEventId(createClientEventId());
                }}>
                Regenerate
              </button>
            </div>
          </div>
          <label>
            Leaderboard ID
            <input name="leaderboardId" maxLength={80} autoComplete="off" placeholder="global" defaultValue="global" pattern="[A-Za-z0-9._:-]+" />
          </label>
          <label>
            Player / Item ID
            <input name="itemId" required maxLength={120} autoComplete="off" placeholder="player-1001" pattern="[A-Za-z0-9._:-]+" />
          </label>
          <label>
            Display name
            <input name="displayName" maxLength={240} autoComplete="off" placeholder="Anna Kowalska" />
          </label>
          <label>
            Score mode
            <select
              value={mode}
              onChange={(changeEvent) => {
                setMode(changeEvent.target.value as 'delta' | 'absoluteScore');
              }}
            >
              <option value="delta">Delta increment/decrement</option>
              <option value="absoluteScore">Absolute score replacement</option>
            </select>
          </label>
          <label>
            {scoreLabel}
            <input name="score" required type="number" step="0.01" placeholder="125" />
          </label>
        </div>
        <div className="form-actions">
          <button type="submit" disabled={mutation.isPending}>
            {mutation.isPending ? 'Publishing...' : 'Publish event'}
          </button>
        </div>
      </form>
    </section>
  );
}
